#!/bin/bash
# Build dist/LeRTX.app (and dist/LeRTX-<version>.dmg) from this checkout.
#
# Usage: desktop/packaging/macos/build.sh [version]
# Run from anywhere; paths are resolved relative to this script's location.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
VERSION="${1:-0.2.0}"

DIST="$ROOT/dist"
APP="$DIST/LeRTX.app"
CONTENTS="$APP/Contents"
RESOURCES_APP="$CONTENTS/Resources/app"

echo "Building $APP (version $VERSION)"
rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$RESOURCES_APP/desktop" "$RESOURCES_APP/docs/user"

sed "s/__VERSION__/$VERSION/g" "$SCRIPT_DIR/Info.plist.in" > "$CONTENTS/Info.plist"

install -m 755 "$SCRIPT_DIR/launcher.sh" "$CONTENTS/MacOS/LeRTX"

cp "$ROOT/desktop/manage.py" "$RESOURCES_APP/desktop/manage.py"
cp "$ROOT/desktop/README.md" "$RESOURCES_APP/desktop/README.md"
cp -R "$ROOT/desktop/source" "$RESOURCES_APP/desktop/source"
cp -R "$ROOT/desktop/locks" "$RESOURCES_APP/desktop/locks"
cp -R "$ROOT/desktop/wheels" "$RESOURCES_APP/desktop/wheels"
cp "$ROOT/docs/user/hardware.md" "$RESOURCES_APP/docs/user/hardware.md"

# Runtime-generated bytecode caches from this build machine are not part of
# the shipped source and would just be stale next to whatever the app
# regenerates itself under Application Support.
find "$RESOURCES_APP" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find "$RESOURCES_APP" -name "*.pyc" -delete 2>/dev/null || true

echo "App bundle created: $APP"

if command -v hdiutil >/dev/null 2>&1; then
    DMG="$DIST/LeRTX-$VERSION.dmg"
    rm -f "$DMG"
    hdiutil create -volname "LeRTX" -srcfolder "$APP" -ov -format UDZO "$DMG"
    echo "Disk image created: $DMG"
else
    echo "hdiutil not found; skipping .dmg creation (app bundle is still usable directly)."
fi
